# Generated by Django 5.2.12 on 2026-03-05 23:47

import django.db.models.deletion
import pipeline.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=pipeline.models.default_expiry)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_role', models.CharField(choices=[('RAW_FASTQ', 'Raw FASTQ'), ('COUNT_MATRIX', 'Count Matrix'), ('H5AD_PSEUDO', 'H5AD Pseudo-scRNA'), ('HE_IMAGE_USER', 'H&E Image (User)'), ('HE_IMAGE_GENERIC', 'H&E Image (Generic)')], max_length=30)),
                ('local_path', models.CharField(max_length=500)),
                ('is_user_uploaded', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to='pipeline.session')),
            ],
            options={
                'db_table': 'file_asset',
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='pipeline.session')),
            ],
            options={
                'db_table': 'analysis_job',
            },
        ),
    ]
