# Generated by Django 5.2.12 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='file_role',
            field=models.CharField(choices=[('RAW_FASTQ', 'Raw FASTQ'), ('COUNT_MATRIX', 'Count Matrix'), ('H5AD_PSEUDO', 'H5AD Pseudo-scRNA'), ('HE_IMAGE_USER', 'H&E Image (User)'), ('HE_IMAGE_GENERIC', 'H&E Image (Generic)'), ('CUSTOM_GENOME_FASTA', 'Custom Genome FASTA'), ('CUSTOM_GENOME_ANNOTATION', 'Custom Genome Annotation')], max_length=30),
        ),
    ]
