# Generated by Django 5.2.12 on 2026-03-08 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_alter_fileasset_file_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='file_role',
            field=models.CharField(choices=[('RAW_FASTQ', 'Raw FASTQ'), ('COUNT_MATRIX', 'Count Matrix'), ('H5AD_PSEUDO', 'H5AD Pseudo-scRNA'), ('HE_IMAGE_USER', 'H&E Image (User)'), ('HE_IMAGE_GENERIC', 'H&E Image (Generic)'), ('CUSTOM_GENOME_FASTA', 'Custom Genome FASTA'), ('CUSTOM_GENOME_ANNOTATION', 'Custom Genome Annotation'), ('METADATA_CSV', 'Metadata CSV')], max_length=30),
        ),
        migrations.CreateModel(
            name='AnalysisSubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_type', models.CharField(blank=True, choices=[('single', 'Single-End'), ('paired', 'Paired-End')], max_length=10)),
                ('strandedness', models.CharField(choices=[('unstranded', 'Unstranded'), ('fr-firststrand', 'Forward-Reverse (fr-firststrand)'), ('fr-secondstrand', 'Forward-Reverse (fr-secondstrand)')], default='unstranded', max_length=20)),
                ('reference_genome', models.CharField(blank=True, max_length=100)),
                ('custom_genome_name', models.CharField(blank=True, max_length=200)),
                ('metadata_mode', models.CharField(blank=True, choices=[('upload', 'Upload CSV'), ('manual', 'Manual Assignment')], max_length=10)),
                ('adjusted_pvalue', models.FloatField(default=0.05)),
                ('min_log2fc', models.FloatField(default=-1.0)),
                ('max_log2fc', models.FloatField(default=1.0)),
                ('metadata_payload', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pipeline.session')),
            ],
            options={
                'db_table': 'analysis_submission',
            },
        ),
        migrations.AddField(
            model_name='fileasset',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to='pipeline.analysissubmission'),
        ),
    ]
