# Generated by Django 5.2.12 on 2026-03-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_fileasset_file_role_analysissubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissubmission',
            name='input_data_type',
            field=models.CharField(choices=[('fastq', 'FASTQ Files'), ('alignment', 'BAM/CRAM Alignment'), ('matrix', 'Count Matrix')], default='fastq', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_role',
            field=models.CharField(choices=[('RAW_FASTQ', 'Raw FASTQ'), ('ALIGNMENT_BAM', 'Alignment BAM/CRAM'), ('USER_COUNT_MATRIX', 'User Count Matrix'), ('COUNT_MATRIX', 'Count Matrix'), ('H5AD_PSEUDO', 'H5AD Pseudo-scRNA'), ('HE_IMAGE_USER', 'H&E Image (User)'), ('HE_IMAGE_GENERIC', 'H&E Image (Generic)'), ('CUSTOM_GENOME_FASTA', 'Custom Genome FASTA'), ('CUSTOM_GENOME_ANNOTATION', 'Custom Genome Annotation'), ('METADATA_CSV', 'Metadata CSV')], max_length=30),
        ),
    ]
