# Generated by Django 5.2.12 on 2026-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_add_output_file_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissubmission',
            name='assay_type',
            field=models.CharField(choices=[('standard_rna', 'Standard RNA-Seq (Poly-A)'), ('small_rna', 'Small RNA / miRNA'), ('chip_seq', 'ChIP-seq'), ('methylation', 'DNA Methylation (Bisulfite-seq)')], default='standard_rna', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_role',
            field=models.CharField(choices=[('RAW_FASTQ', 'Raw FASTQ'), ('ALIGNMENT_BAM', 'Alignment BAM/CRAM'), ('USER_COUNT_MATRIX', 'User Count Matrix'), ('COUNT_MATRIX', 'Count Matrix'), ('NORMALIZED_COUNTS', 'Normalized Counts'), ('DEG_TABLE', 'Differential Expression Table'), ('MULTIQC_REPORT', 'MultiQC Report'), ('H5AD_PSEUDO', 'H5AD Pseudo-scRNA'), ('HE_IMAGE_USER', 'H&E Image (User)'), ('HE_IMAGE_GENERIC', 'H&E Image (Generic)'), ('CUSTOM_GENOME_FASTA', 'Custom Genome FASTA'), ('CUSTOM_GENOME_ANNOTATION', 'Custom Genome Annotation'), ('METADATA_CSV', 'Metadata CSV'), ('PEAK_FILE', 'ChIP-seq Peak File'), ('METHYLATION_REPORT', 'Methylation Report')], max_length=30),
        ),
    ]
