# Generated by Django 5.2.12 on 2026-03-20 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_add_assay_type_and_track_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='is_core_pipeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pipeline.analysissubmission'),
        ),
        migrations.CreateModel(
            name='ModuleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_results', to='pipeline.analysissubmission')),
            ],
            options={
                'db_table': 'module_result',
            },
        ),
    ]
