# Generated by Django 5.2.12 on 2026-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_v1_2_workspace_hub_paradigm'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissubmission',
            name='submission_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
