# Generated by Django 5.2.12 on 2026-03-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_add_submission_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleResult',
        ),
    ]
