# Generated by Django 5.2.12 on 2026-03-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_remove_moduleresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissubmission',
            name='tcga_project_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='analysissubmission',
            name='input_data_type',
            field=models.CharField(choices=[('fastq', 'FASTQ Files'), ('alignment', 'BAM/CRAM Alignment'), ('matrix', 'Count Matrix'), ('tcga', 'TCGA Dataset')], default='fastq', max_length=10),
        ),
    ]
