"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present (development); production sets env vars directly
load_dotenv(BASE_DIR / ".env")

# ── Environment Detection ──
# Set RNASEEK_ENV=production on the production server. Defaults to development.
RNASEEK_ENV = os.environ.get("RNASEEK_ENV", "development")
IS_PRODUCTION = RNASEEK_ENV == "production"

# SECURITY WARNING: keep the secret key used in production secret!
if IS_PRODUCTION:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
    if not SECRET_KEY:
        raise ValueError("DJANGO_SECRET_KEY must be set in production")
else:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-f#6y2$)m)+_2bd$+%c539^1n+b+tvf$@emcc1lwj7d5uc%f3l@",
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "http://localhost:8000"
).split(",")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'django_celery_beat',
    'pipeline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pipeline.middleware.AnonymousSessionMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pipeline.context_processors.session_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# ── Django Channels / WebSocket ──
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if IS_PRODUCTION:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "rnaseek"),
            "USER": os.environ.get("DB_USER", "rnaseek"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serve static files in production without a separate web server
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media (user uploads / pipeline outputs on NFS)
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media")))
MEDIA_URL = '/media/'

# ── Tus Upload (tusd webhook) ──
TUS_DATA_DIR = os.environ.get("TUS_DATA_DIR", str(MEDIA_ROOT / "tusd-data"))
TUS_HOOK_SECRET = os.environ.get("TUS_HOOK_SECRET", "")
if IS_PRODUCTION and not TUS_HOOK_SECRET:
    raise ValueError("TUS_HOOK_SECRET must be set in production")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Celery / Redis ──
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# In development, run Celery tasks asynchronously by default so the HTTP
# response returns immediately and the browser can redirect to the processing
# page.  Set CELERY_EAGER=1 to run tasks synchronously (no worker needed)
# for quick local debugging of task logic — but note this blocks the request.
if not IS_PRODUCTION:
    _eager = os.environ.get("CELERY_EAGER", "0") == "1"
    CELERY_TASK_ALWAYS_EAGER = _eager
    CELERY_TASK_EAGER_PROPAGATES = _eager

# Celery worker concurrency (matches CPU count)
CELERY_WORKER_CONCURRENCY = os.cpu_count() or 4

# ── Celery Asymmetric Queue Routing (Production) ──────────────────
# Routes CPU-intensive pipeline tasks (HISAT2, BWA, Bowtie2) and
# RAM-intensive analytics (DESeq2, WGCNA, rMATS) to separate worker
# pools with different concurrency and memory limits.
# See: systemd/rnaseek-celery-cpu.service  (concurrency=5, 8 threads/tool)
#      systemd/rnaseek-celery-ram.service  (concurrency=4, MemoryMax=96G)
#
# In development (IS_PRODUCTION=False), no routing is applied — all
# tasks go to the default "celery" queue and the single dev worker
# picks them up normally.
if IS_PRODUCTION:
    CELERY_TASK_DEFAULT_QUEUE = "cpu_bound"
    CELERY_TASK_ROUTES = {
        "pipeline.tasks.core.run_core_pipeline": {"queue": "cpu_bound"},
        "pipeline.tasks.core.run_tier2_module": {"queue": "ram_bound"},
        "pipeline.tasks.core.purge_expired_sessions": {"queue": "cpu_bound"},
    }

# ── Production Security Hardening ──
if IS_PRODUCTION:
    # Nginx terminates SSL and forwards via X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Exempt internal service-to-service webhook paths from SSL redirect
    # (tusd calls Django over localhost HTTP, not through Nginx)
    SECURE_REDIRECT_EXEMPT = [r"^api/tusd-hooks/"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ── Logging ──
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "daphne": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "pipeline": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
