#!/usr/bin/env bash
# ============================================================
# RNAseek — Production OS & Network Tuning
# ============================================================
# Target: 48-core / 128 GB RAM / NVMe bare-metal Ubuntu host.
# Tunes TCP (BBR), memory, and kernel parameters for:
#   - Maximum WAN upload throughput (50 GB+ FASTQ files)
#   - OOM-resistant memory behavior for heavy R workloads
#
# Usage:   sudo bash scripts/tune-production-os.sh
# Persist: Writes to /etc/sysctl.d/ so changes survive reboots.
# Verify:  sysctl net.ipv4.tcp_congestion_control
# ============================================================

set -euo pipefail

# ── Safety: refuse to run on development machines ──────────────
MIN_CORES=16
CORES=$(nproc)
if [[ "$CORES" -lt "$MIN_CORES" ]]; then
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║  ABORT: Detected $CORES CPU cores.                          ║"
    echo "║  This script is for the 48-core PRODUCTION server only.     ║"
    echo "║  Minimum required: $MIN_CORES cores.                        ║"
    echo "║  DO NOT run this on a development laptop.                   ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)."
    exit 1
fi

# ── Ensure tcp_bbr kernel module is loaded ─────────────────────
modprobe tcp_bbr 2>/dev/null || true
if ! grep -q "^tcp_bbr" /etc/modules-load.d/*.conf 2>/dev/null; then
    echo "tcp_bbr" > /etc/modules-load.d/tcp-bbr.conf
    echo ">>> Added tcp_bbr to /etc/modules-load.d/tcp-bbr.conf"
fi

SYSCTL_FILE="/etc/sysctl.d/99-rnaseek.conf"
echo ">>> Writing production kernel tuning to $SYSCTL_FILE ..."

cat > "$SYSCTL_FILE" <<'SYSCTL'
# ============================================================
# RNAseek Production Kernel Tuning
# Generated by: scripts/tune-production-os.sh
# Target: 48-core / 128 GB RAM / NVMe host
# ============================================================

# ── 1. TCP BBR Congestion Control ────────────────────────────
# BBR (Bottleneck Bandwidth and RTT) dramatically improves
# throughput on high-latency WAN links vs. the default CUBIC.
# It probes available bandwidth without filling router buffers,
# making it ideal for intercontinental 50 GB+ uploads.
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# ── 2. TCP Buffer / Window Sizes ─────────────────────────────
# Formula: BDP (Bandwidth-Delay Product) = bandwidth × RTT
# For a 10 Gbps link with 100 ms RTT: BDP ≈ 125 MB.
# We set max buffers to 128 MB to cover worst-case BDP.
#
#                                 min    default   max  (bytes)
net.ipv4.tcp_rmem              = 4096   1048576   134217728
net.ipv4.tcp_wmem              = 4096   1048576   134217728

# Global socket buffer ceilings
net.core.rmem_max              = 134217728
net.core.wmem_max              = 134217728
net.core.rmem_default          = 1048576
net.core.wmem_default          = 1048576

# TCP memory pages (min / pressure / max)
# ~4 GB of kernel memory for TCP buffers on 128 GB host
net.ipv4.tcp_mem               = 786432 1048576 1572864

# ── 3. Connection & Backlog Tuning ───────────────────────────
# Handle bursts of incoming TUS chunk uploads and parallel
# connections from tus-js-client (parallelUploads: 6).
net.core.somaxconn             = 65535
net.core.netdev_max_backlog    = 65535
net.ipv4.tcp_max_syn_backlog   = 65535

# Allow more simultaneous TIME_WAIT sockets (upload churn)
net.ipv4.tcp_max_tw_buckets    = 2000000
net.ipv4.tcp_tw_reuse          = 1

# ── 4. TCP Fast Open & Keepalive ─────────────────────────────
# TFO (flag 3 = both client & server) reduces handshake latency
# for repeat uploaders reconnecting from the same machine.
net.ipv4.tcp_fastopen          = 3

# Detect dead connections faster (important for long uploads)
net.ipv4.tcp_keepalive_time    = 60
net.ipv4.tcp_keepalive_intvl   = 10
net.ipv4.tcp_keepalive_probes  = 6

# ── 5. TCP Window Scaling & SACK ─────────────────────────────
# Required for the large window sizes (128 MB) above to work.
net.ipv4.tcp_window_scaling    = 1
net.ipv4.tcp_timestamps        = 1
net.ipv4.tcp_sack              = 1

# ── 6. VM / Memory Tuning (OOM Prevention) ───────────────────
# overcommit_memory=1: Always overcommit. R (via rpy2) uses
# fork() which temporarily doubles virtual memory. Without this,
# the kernel may refuse fork() even when physical RAM suffices.
vm.overcommit_memory           = 1

# Low swappiness: prefer keeping R datasets in RAM over
# swapping to NVMe. 10 = only swap under real pressure.
vm.swappiness                  = 10

# Flush dirty pages to NVMe sooner, preventing large memory
# spikes from buffered I/O during pipeline output writes.
vm.dirty_ratio                 = 10
vm.dirty_background_ratio      = 5

# ── 7. File Descriptor Limits ────────────────────────────────
# Many concurrent TUS uploads + Celery workers + Redis
fs.file-max                    = 2097152
fs.nr_open                     = 2097152
SYSCTL

echo ">>> Applying sysctl settings ..."
sysctl --system

# ── Verify BBR is active ──────────────────────────────────────
ACTIVE_CC=$(sysctl -n net.ipv4.tcp_congestion_control)
if [[ "$ACTIVE_CC" == "bbr" ]]; then
    echo "✓ TCP BBR congestion control is ACTIVE."
else
    echo "✗ WARNING: TCP congestion is '$ACTIVE_CC', not 'bbr'."
    echo "  Attempting to enable BBR ..."
    sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
fi

# ── Set ulimits for the ubuntu service user ───────────────────
LIMITS_FILE="/etc/security/limits.d/99-rnaseek.conf"
cat > "$LIMITS_FILE" <<'LIMITS'
# RNAseek — ulimits for the application user
ubuntu  soft  nofile  1048576
ubuntu  hard  nofile  1048576
ubuntu  soft  nproc   65535
ubuntu  hard  nproc   65535
LIMITS
echo ">>> User ulimits written to $LIMITS_FILE"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Production OS tuning applied. Changes persist across reboots."
echo "  Verify:  sysctl net.ipv4.tcp_congestion_control"
echo "           sysctl net.ipv4.tcp_rmem"
echo "           cat /proc/sys/net/core/rmem_max"
echo "════════════════════════════════════════════════════════════"
